### ISSUE TITLE
Nondeterministic events

### ISSUE THREAD

**Issue by vrish88** [gocardless/statesman#129]
Hi de ho!

We pulled statesman into a project of ours and thus far found it quiet easy to use. However, we ran into a case that statesman doesn't yet support.

We have orders which are unpaid state until the amount paid reaches the order total at which they are paid. So something like (in pseudo statesman):

```ruby
event :make_payment do |order
  next_state = order.total > order.amount_paid ? :unpaid ? :paid
  transition_to next_state
end
```

Would something like this be in statesman's future? I think that with these nondeterministic events we'd still be able to use methods like `#allowed_transitions`, `#available_events`, `#current_state`, etc.

**Comment by isaacseymour** [comment]
Hi @vrish88, I don't think this kind of functionality will ever be part of Statesman, as it can easily be accomplished with a service object or method on the order object:
```ruby
class Order
  ...
  def make_payment
    state_machine.transition_to!(total > amount_paid ? :unpaid : :paid)
  end
end
```
which is much more obvious and easy to understand than just seeing `.trigger!(:make_payment)` and having to dig into the state machine to find out why it's ending up in `:unpaid` rather than `:paid`.

Hope this answers your question - let me know if this doesn't cover the case you were thinking of.
