### ISSUE TITLE
NoMethodError: undefined method `foreign_key' for nil:NilClass

### ISSUE THREAD

**Issue by adamklaff** [gocardless/statesman#161]
This may be entirely due to user error on my part, but I'm honestly stumped. Any help would be appreciated. I'm on Rails 4.1.8

I can get the initial state of a record, but when I attempt to call the in_state method I get the following error:

User.in_state(:updated)
NoMethodError: undefined method `foreign_key' for nil:NilClass

I have a user model user.rb with:

```ruby
has_many :transitions, class_name: "UserTransition"

delegate :can_transition_to?, :transition_to!, :transition_to, :current_state,
		to: :state_machine

def state_machine
     @state_machine ||= UserStateMachine.new(self, transition_class: UserTransition, association_name: :transitions)
end

private
def self.transition_class
	UserTransition
end
def self.initial_state
    :pending
end
```

I have a UserTransition model user_transition.rb with:

```ruby
class UserTransition < ActiveRecord::Base
	include Statesman::Adapters::ActiveRecordTransition

	belongs_to :user, inverse_of: :transitions

end
```

and finally UserStateMachine being included from user_state_machine.rb with:

```ruby
class UserStateMachine
	include Statesman::Machine

	state :pending, initial: true
	state :updated
	state :in_progress

end
```

I'm using Statesman in an initializer with:

```ruby
Statesman.configure do
  storage_adapter(Statesman::Adapters::ActiveRecord)
end
```

**Comment by isaacseymour** [comment]
Hi @adamklaff sorry for the slow response. The reason you're having this problem is because Statesman assumes that your transition association will be named `:user_transitions`. #131 added support for overriding this name, documented in the readme [just above here](https://github.com/gocardless/statesman#modelin_statestate_1-state_2-etc). Essentially you just need to add

```ruby
def self.transition_name
  :transitions
end
```
to your `User` model and it'll all work fine.

**Comment by adamklaff** [comment]
Thanks!
