### ISSUE TITLE
Model/Machine Responsibility

### ISSUE THREAD

**Issue by spc9999** [gocardless/statesman#175]
First up, awesome library! I love the design, building separation of the machine from the model, and breaking out guard definitions independent of events, terrific.

I'm wondering what the 'statesman way' is for methods which will trigger transitions and and update model attributes. Are you adding these on the state machine or the model?

For example, following on your Order sample code, consider a couple of methods which interact with both the machine state and model attributes. These would be called by an external class, lets say a batch shipping manager:

````ruby
    def shipped(tracking_number)
        fail('the machine say no') unless state_machine.can_transition_to?(:shipped)
        order.tracking_number = tracking_number
        fail('cant save wont save') unless order.save
        state_machine.transition_to(:shipped)                     
    end       

    def failed_to_ship(stock_reason)
        order.status = cancelled
        order.send_customer_email(stock_reason)
        state_machine.transition_to(:failed)
    end
````
On the one hand, I will be calling state transitions from within my order model, on the other I will be updating model attributes or calling model methods from my state machine. Have you picked which of the objects is most appropriate for state/model changes? I understand there is a callback mechanism in the state machine, but there are times when transition results and model validation may be necessary within the same transaction, or I may want a definitive return to the object initiating state change. A gem such as AASM binds everything together, I'm trying to understand how you maintain separate responsibilities with these types of interactions.

**Comment by greysteil** [comment]
Typically we put any updates that are a fundamental part of the transition into state machine callbacks. Those updates really belong to the state transition logic, not to the model, so they make most sense there. Further, you're within a transaction when callbacks are run, so you can rely on statesman to ensure you don't get inconsistent data. I'd count adding a `tracking_number` as a fundamental part of the transition to `shipped`. 

Other operations, like sending an email to the customer, aren't as fundamental to the transition. A good rule here is if you'd ever not want to perform the action when performing the transition then in doesn't belong in the state machine.

Finally, we've found ourselves storing more and more details on the transition objects rather than the owner objects. If you have states which can be cycled through multiple times (e.g., at GoCardless failed payments can be retried, and loop through the same set of states again) you might want to think about whether this flow would lead you to overwrite anything on the owner object that you could have stored on the transition instead.
