### ISSUE TITLE
Migrating from 0.6.3 - multiple state machines no longer supported?

### ISSUE THREAD

**Issue by hamaker** [gocardless/statesman#178]
Hi there,
I'm currently migrating an application that used version 0.6.3 of statesman to the newest version. It uses a model with two state machines in it, but I wasn't sure that's still supported. Looking at the ActiveRecordQueries, it seems to me that multiple state machines is no longer supported, as a class can implement only a single `self.initial_state` and `self.transition_class`, and these properties don't seem to be taken from the state machine. Is that right, or is there some way around this that I missed? If this is the case, I was wondering if multi-statemachine support was dropped on purpose? 

Thanks,
Niels

**Comment by isaacseymour** [comment]
`ActiveRecordQueries` will only work for the state machine which you define `initial_state` and `transition_class` to relate to (I think this has always been the case). Pretty sure you can still have multiple state machines on the same model, but you just won't be able to use `(not_)in_state` for the second one.

**Comment by hamaker** [comment]
Thanks for the quick response! 
One of the issues I was having was that I can no longer override the `transition_name` of the second state machine (the table name is namespaced as I'm using this within an engine). So overriding the association properties, as described in [this section of the docs](https://github.com/gocardless/statesman#model-scopes), only works for the main state machine and not for secondary ones, right, which should stick to defaults?
We had trouble with `use_most_recent_column?` breaking, or using the wrong table, for the second state machine.

**Comment by hamaker** [comment]
Oh, sorry, I was confused, I see now what is going on.

**Comment by hamaker** [comment]
My confusion was caused by the state machine and the ActiveRecordQueries not sharing any information about the configuration. Would you be interested if we put in a pull request for something like that? That in stead of setting the initial_state and transition_class, you could set the query_state_machine you'd want to use for it, and it would get all the settings off of that?

**Comment by isaacseymour** [comment]
Hmm, the difficulty there is that the state machine to use is generally defined on an instance, rather than the class itself (we use this internally to pick which state machine to use based on an attribute of the model). If you can make it work both ways that would be a nice addition though!

**Comment by lleolin** [comment]
I need this to work for my app and I've been pondering the best way to get it to work.

Right now I have a terrible hack where I use STI and polymorphism with a single transitions table. This way I can narrow transitions down to e.g. `type = 'ConfirmationTransition' AND transitional_type = 'Post'`. This approach falls apart using `not_in_state` even with additional hacks. That's really where this whole thing fell apart for me, I thought my hacks were working until I realized I can't easily retrieve records that are not in a particular state machine's state.

The easiest way I can imagine to do it, would be to persist a record of a state machine configuration that can be looked up based on the model containing that state machine. This would also permit me to use multiple instances of the same machine on one class as long as I namespace them. So, essentially, a transitions record would belong to a state_machines record. But a state_machines record would essentially belong to a model class instead of a model instance. I'm a little uncertain about this, it feels kind of off, but it seems reasonable in my head.

A method like `not_in_<state_machine>_state` would have to be in place to scope not_in_state queries to a specific state machine instance. Generating methods like this might require a class-level declaration method for state machines e.g. `state_machine :confirmation, class_name: 'ConfirmationStateMachine'`.

I think there would need to be some pretty significant revisions to statesman for this to work, would easily break backwards compatibility. I want to get this going because my project needs it, but I'm hesitant to start hacking away at it without fully understanding the mission. And there's still the question of whether these changes would appreciated or if I would be adding complexity that few people need.

**Comment by chaadow** [comment]
Hi, I've made a gem that handles this scenario for statesman for those interested https://github.com/chaadow/statesman-multi_state
