### ISSUE TITLE
Documentation missing for Events

### ISSUE THREAD

**Issue by KBalderson** [gocardless/statesman#183]
There is no documentation for events.

I may be able to provide this as I uncover their use with a few new features I am building, but it may be better left to those who wrote the code.

**Comment by isaacseymour** [comment]
Hi @KBalderson, sorry for the slow response on this one. We removed the docs for events in #142, mostly because we're not keen on them. The way I see it, logic for working out which state to transition to does not belong in Statesman - its responsibilities are to:
- enforce constraints (on valid transitions, prevent races);
- record history;
- perform transitions.

The original documentation for events can still be found in #63.

**Comment by KBalderson** [comment]
That makes sense. Does this mean that events will be deprecated?

**Comment by isaacseymour** [comment]
It's hard to decide! Although GC-ers seem to generally be against them*, they were strongly demanded by the rest of the community, and it'd be a pretty big breaking change to remove them. So...maybe :stuck_out_tongue: 

*not that I want to speak for anyone!

**Comment by KBalderson** [comment]
Thanks for the info! I'll keep an eye on it.

**Comment by thoughtpunch** [comment]
@isaacseymour can you add something to the documentation that explains the best pattern for transitioning without events?

**Comment by greysteil** [comment]
Hi @thoughtpunch, we're about to split events out into a separate companion gem, where they can have much clearer documentation and a more complete implementation.

**Comment by greysteil** [comment]
Quick update on this - we've just release v0.0.1 of https://github.com/gocardless/statesman-events, which replicates all of the Events functionality in Statesman v1.3.1, with documentation.
