### ISSUE TITLE
Index with where

### ISSUE THREAD

**Issue by nikolai-b** [gocardless/statesman#209]
Rails added support for the partial index BUT in rails 4.0 they didn't add support to output the `where` part of the index to the schema so any test db isn't created with the `where` part.
This means my tests don't pass.

```
f2api_dev=# \d merchant_delivery_transitions
....
Indexes:
    "index_merchant_delivery_transitions_parent_most_recent" UNIQUE, btree (merchant_delivery_id, most_recent) WHERE most_recent

f2api_test=# \d merchant_delivery_transitions
....
Indexes:
    "index_merchant_delivery_transitions_parent_most_recent" UNIQUE, btree (merchant_delivery_id, most_recent)
```

Could you document that test db will fail or only add the `most_recent` index in newer versions of rails (if it is fixed there)?

**Comment by greysteil** [comment]
Pretty surprised by this - that's a pretty serious Rails bug if it's the case. Not keen to work around or re-document it here if we can avoid it. Are you loading your test database from a `schema.rb` file rather than a `structure.sql`, by any chance? Check out http://edgeguides.rubyonrails.org/active_record_migrations.html#schema-dumping-and-you if so.

**Comment by nikolai-b** [comment]
Yes I am using the `schema.rb`.  I was just confused that it doesn't work.  Just checked and on Rails 4.1.0 and it does put the `where` into the `schema.rb`

```
add_index "blahs", ["name", "a_bool"], name: "index_blahs_on_name_and_a_bool", where: "a_bool", using: :btree
```

 but in rails 4 it does not.

```
add_index "merchant_delivery_transitions", ["merchant_delivery_id", "most_recent"], :name => "index_merchant_delivery_transitions_parent_most_recent", :unique => true
```

**Comment by greysteil** [comment]
Hey, apologies for the delay on this one.

I've taken another quick look at what could be going on on the Rails side. Are you using SQLite for your test setup by any chance? If so, the issue is probably that https://github.com/rails/rails/pull/13350 only went into Rails 4.1, combined with https://github.com/rails/rails/issues/18106. That could explain the schema dumping issue.

**Comment by nikolai-b** [comment]
Turns out it was nothing to do with Rails
https://github.com/rgeo/activerecord-postgis-adapter/issues/142
