### ISSUE TITLE
Rails 5 undefined method cast_type Error

### ISSUE THREAD

**Issue by joaomdmoura** [gocardless/statesman#222]
I've tried to setup Statesman on a Rails 5 app, followed the Readme instructions but ended up with the following error:

```
NoMethodError (undefined method `cast_type' for #<ActiveRecord::ConnectionAdapters::PostgreSQLColumn:0x007fa0261cb290>):

app/models/order.rb:17:in `new'
app/models/order.rb:17:in `state_machine'
app/models/order.rb:14:in `current_state'
```

I'm using the PostgreSQL JSON column, but even if I try to stick to the `serialize` old way it still returns the same error.

**Comment by spikeheap** [comment]
I had the same issue, although with the MySQL adaptor, on v1.3.1 of Statesman. 

It looks like the `cast_type` column was removed in [this commit to ActiveRecord 5](https://github.com/rails/rails/commit/158c7eb1d61a28452e0aafd1e05314352eea2749#diff-ece1d9e4cf3db41b2c394e2acfcc2330), but that problem was fixed by https://github.com/gocardless/statesman/commit/95feb6a5956c860400d2118ec5566ff9178b783c, which was released in `v2.0.1` of statesman.

Upgrading to 2.0.1 or later should resolve this issue for you, though you'll want to check the [changelog](https://github.com/gocardless/statesman/blob/v2.0.1/CHANGELOG.md) as there are a few breaking changes.
