### ISSUE TITLE
Callback Best Practices

### ISSUE THREAD

**Issue by vassilevsky** [gocardless/statesman#237]
I understand that I can put code in callbacks and it will be run when the transition occurs.

But what _should_ I put into callbacks? And, most importantly, what I should *not* put there?

I couldn't find any definitive answers to these questions anywhere. My current understanding is that callback are for code that updates event timestamps on the model itself and maybe logs it. More complex logic such as user notifications should not be put into callbacks.

Obviously you have more experience with state machines than I do so what are your recommendations / guidelines on the topic?

**Comment by Sinjo** [comment]
@vassilevsky You've certainly picked up on a contentious topic! 😛 Let's say this one's about as clear cut as "When should you use callbacks on Rails models?"

Inside GC, our answer has increasingly been to move away from callback approaches and towards classes that wrap a sequence of actions together (usually inside a database transaction). The main two reasons are:

  - We've come to prefer explicit behaviour over implicit. When you're implementing new code, it's easy to be bitten by "extras" that come with callbacks when you call `save` or `transition_to`. Often when these things are written, they seem like totally global actions that you would definitely want to run on every save/transition. Which leads to...
  - We've found over time that more and more conditionals find their way into callbacks. "This one shouldn't run for admins.", "This one is only for people paying in <country>", etc. At some point it becomes really hard to track down which code will be executed when you perform a transition with different properties set. You don't even have the clarity of a big block of if/else statements, because the conditionals are spread across all the different callbacks.

There's no one recommendation I can give you, and I'm sure the line would be slightly different for everyone at GC. Hopefully you can at least be aware of the pitfalls, and know when to move things out of callbacks before too much complexity ends up there!

**Comment by hmac** [comment]
Closing because I think this is answered - feel free to reopen if you've still got questions!

**Comment by vassilevsky** [comment]
Thank you 🙏
Your experience is the same as mine 🙃
