### ISSUE TITLE
are state machines composable?

### ISSUE THREAD

**Issue by BrianHicks** [gocardless/statesman#303]
I’m looking at statesman for a project. In this, we have a larger state machine comprised of several smaller state machines that get composed together in different ways.

How would you recommend I approach this? Is statesman an appropriate tool here?

**Comment by danwakefield** [comment]
Hi @BrianHicks 

It would really helpful if you gave more context / some examples of the
issue's you are having.

Since Statesman's state machines are independant classes there is no reason that
you cannot use more than one together.

For example, If you had a class to represent a visit to a restaurant
it could contain separate machines for different courses.
The Main Course state machine could be blocked from moving to Dessert before
the until it had been eaten and the plates cleared.
And none of the Machines related to Food would prevent more drinks being ordered.

A rough sketch would be 

```
Ordered -> Starter -> Main -> Dessert
              |
              V
           preparing
              |
              V
            cooked
              |
              V
          delivered
              |
              V
            eaten
              |
              V
        plate removed
```

**Comment by BrianHicks** [comment]
ah, that makes sense and answers my question. Thank you!
